"""Optimization-level classification: the analyst-facing priority framing that sits
ABOVE individual task categories (404_fix, meta_tag_reoptimization, etc.) -- "is this a
key fix, a quick win, or ongoing content work" is a more immediately understandable
question for a client/analyst than a raw category name or severity score.

Five levels, in the order an analyst actually works them:
  1. benchmarking     -- foundational research before any fix work starts (prompt
                          analysis, keyword research). Not generated by any rule engine
                          -- no data source for this exists yet -- so every new campaign
                          gets ONE seeded task for it in week 1 (see services.py). Purely
                          one-time -- ongoing tracking of this happens in the reporting
                          artifacts/dashboard, not as a separate recurring task here.
  2. key_fix          -- foundational technical/systemic problems: if these aren't
                          fixed, nothing else on the site can be trusted (crawl errors,
                          indexation blocking, GA4 tracking/mobile issues investigated
                          at a systemic level, schema recommendations alongside the
                          technical audit).
  3. quick_win        -- real, but narrower, lower-effort optimizations on pages that
                          are otherwise already working (meta rewrites, CTR, bounce,
                          anchor-text optimization on service/product/target pages).
  4. ongoing_content   -- the recurring, month-over-month work: expanding existing
                          content, writing new content, and LLM/GEO-oriented content
                          (on-site and third-party/social) alongside it.
  5. reporting         -- the recurring client-facing cadence (weekly reports, monthly
                          business reviews) -- NOT part of the sequential phase queue
                          the other four levels share. It runs on its own real-calendar
                          schedule (every Wednesday) in parallel with whatever phase the
                          main sequence is in -- see app/rules/reporting_rules.py.

This is a DEFAULT, not a fixed rule -- every task's optimization_level is a plain
editable Task column (see app/models.py), changeable per-task from the UI or chat at
any time. CATEGORY_DEFAULTS below only decides what a freshly generated task starts
as; it never overrides an analyst's own choice on an existing task (see
app/services.py's _apply_default_optimization_levels, which only ever sets this on
tasks that don't already have a level).
"""
from __future__ import annotations

OPTIMIZATION_LEVELS = ["benchmarking", "key_fix", "quick_win", "ongoing_content", "reporting"]

OPTIMIZATION_LEVEL_LABELS = {
    "benchmarking": "Benchmarking",
    "key_fix": "Key Fix",
    "quick_win": "Quick Win",
    "ongoing_content": "Ongoing Content",
    "reporting": "Reporting",
}

# Categories that are seeded once per campaign and never regenerated/deleted by
# regenerate_content_plan's cleanup (unlike the monthly content pipeline, which is
# fully regenerated every call) -- see services.py's ensure_benchmarking_task /
# ensure_anchor_optimization_task / ensure_schema_recommendations_task.
STANDING_TASK_CATEGORIES = {
    "prompt_keyword_benchmarking", "anchor_optimization", "schema_recommendations", "url_structure_optimization",
}

# category -> default optimization_level for a freshly generated task. Systemic/
# root-cause investigations (high effort_tier, "fix this or nothing else matters")
# are key_fix; individual-page, narrower optimizations are quick_win; anything that
# adds or expands content is ongoing_content. Categories not listed here (e.g. a
# custom chat-created task) simply get no default -- left for the analyst to set.
CATEGORY_DEFAULTS = {
    # crawl
    "technical_audit": "key_fix",
    "indexation_blocking": "key_fix",
    "server_error": "key_fix",
    "404_fix": "key_fix",
    "redirect_inlink_update": "key_fix",
    # gsc
    "meta_tag_reoptimization": "quick_win",
    "ctr_optimization": "quick_win",
    "content_expansion": "ongoing_content",
    # ga4 -- low_mobile_share/low_key_events/ui_ux_review all follow technical work in
    # the Key Fix phase (per the analyst's own ordering: "technical must [be 2nd week],
    # rest of the UI/UX and other tasks can come after technical"); high_exit_rate is
    # the one GA4 check that's a genuine Quick Win, not a foundational fix.
    "low_mobile_share": "key_fix",
    "low_key_events": "key_fix",
    "ui_ux_review": "key_fix",
    "high_exit_rate": "quick_win",
    "schema_recommendations": "key_fix",
    "url_structure_optimization": "key_fix",
    # content_plan (recurring)
    "content_topic_research": "ongoing_content",
    "content_brief_finalization": "ongoing_content",
    "content_creation": "ongoing_content",
    "page_optimization": "ongoing_content",
    "wasted_impressions": "ongoing_content",
    "new_page_creation": "ongoing_content",
    "llm_optimization": "ongoing_content",
    # one-off seeded tasks (see services.py)
    "prompt_keyword_benchmarking": "benchmarking",
    "anchor_optimization": "quick_win",
    # reporting cadence (see app/rules/reporting_rules.py) -- calendar-anchored, not
    # part of the sequential phase queue the other levels share.
    "performance_dashboard": "reporting",
    "weekly_report": "reporting",
    "monthly_report_mbr": "reporting",
}


def default_optimization_level(category: str) -> str | None:
    return CATEGORY_DEFAULTS.get(category)
